Fixed the NFC COVID certificate scanner
eu-digital-green-certificates/dgca-verifier-app-android pull request #237
Opened 2021-11-04 12:22 UTC by Giraut

This is a fix to let the DGCA Verifier app correctly interpret the string of a COVID certificate QR code stored on an NFC tag as a plain text NDEF record (urn:nfc:wkt:T). The app didn't work because it failed to strip out the language code from the NDEF record payload in NdefParser.kt. Also, it choked on a piece of code that couldn't determine the ISO country code in CodeReaderFragment.kt.

2021-12-22 07:52 UTC, Thebys commented
Can we get this reviewed and merged please? Thank you. Let me know if I can help. Best regards, Tomáš Biheler, CZ. @MykhailoNester

2021-12-29 17:04 UTC, craftbyte commented
I think it would also be a good idea to go through all NDEF records and find the first text record (maybe also check if it begins with "HC1:"). Take a look at https://github.com/eu-digital-green-certificates/dgca-verifier-app-ios/pull/126/commits/fa18c9e0f69ee5482f15f792fb501286a53a4d0c#diff-41e8a708bc456b25459fcdaedd3f61299ab9404b764ed54bd6b8b2d69769a364R205 for example.

2021-12-29 20:43 UTC, Giraut commented
> I think it would also be a good idea to go through all NDEF records and find the first text record (maybe also check if it begins with "HC1:"). Take a look at [eu-digital-green-certificates/dgca-verifier-app-ios@fa18c9e#diff-41e8a708bc456b25459fcdaedd3f61299ab9404b764ed54bd6b8b2d69769a364R205](https://github.com/eu-digital-green-certificates/dgca-verifier-app-ios/commit/fa18c9e0f69ee5482f15f792fb501286a53a4d0c#diff-41e8a708bc456b25459fcdaedd3f61299ab9404b764ed54bd6b8b2d69769a364R205) for example.

Yes, that is also what I want. That way the tag could contain several records, one of which being the scannable version of the certificate.

Currently I carry my COVID certificate as a smart poster, readable by any cellphone, in my NFC implant (you can see what it looks like here: https://forum.dangerousthings.com/t/covid-certificate-and-other-large-ndefs/11544/17). Ideally, I'd like to add the scannable text-only certificate as another record in the smart poster, so my implant is usable both with a NFC-enabled verifier all and with a vanilla smartphone without any app.

However, seeing as though the review process for the DGCA verifier app is quite slow, and the national authorities basing their national verifier apps on this implementation aren't much faster, I decided to introduce a pull request with as few changes as possible - essentially just the bare minimum fix to get it working again with a dedicated NDEF record - to avoid spooking people and maximize the chance of it being adopted. Then my plan was to propose the same change as yours later on. But it seems I'm not the only one interested in this :)

One caveat: I don't think encoded certificate are guaranteed to start with HC1. It just so happens that most do, but it's not a foolproof marker. A better way would be to simply try to decode all the text records present in the tag and display the first one that decodes properly.

2021-12-29 23:04 UTC, craftbyte commented
@Giraut all the certificates have to start with HC1: as per the specification. See section 4.2.2 in https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v1_en.pdf

2021-12-30 11:22 UTC, ascheibal approved these changes

2022-01-25 22:02 UTC, darkojelen requested changes
**NdefParser.kt** is OK in this pull request. It is very urgent to be fix and must be merged ASAP. Our Production Slovenian dgca-verifier-app with NFC is broken because programmers did not know about this bug.

But **CodeReaderFragment.kt** in this pull request is **not ok**. Without try catch around findNavController().navigate(action) line it crash if fragment DetailedVerificationResult is on screen when NFC reading start.
If you touch Done button or wait to close itself and then read NFC again it work normally, but if you try NFC reading too fast it crash.

It would be even better if next NFC reading close fragment automatically.

`    fun onNdefMessageReceived(qrCodeText: String) {
        try {
        val action =
            CodeReaderFragmentDirections.actionCodeReaderFragmentToVerificationDialogFragment(
                qrCodeText,
                binding.countrySelector.selectedItem?.toString() ?: ""
            )
        findNavController().navigate(action)
        } catch (ex: Exception) {
            Timber.d("action_codeReaderFragment_to_verificationDialogFragment cannot be found from the current destination Destination.")
        }

    }
`

2022-01-26 08:29 UTC, Giraut commented
> But **CodeReaderFragment.kt** in this pull request is **not ok**. Without try catch around findNavController().navigate(action) line it crash if fragment DetailedVerificationResult is on screen when NFC reading start. If you touch Done button or wait to close itself and then read NFC again it work normally, but if you try NFC reading too fast it crash.

You are correct, I overlooked this. I've committed your fix in my fork. Thanks!

2022-01-27 13:48 UTC, Giraut commented
Since nothing seems to be happening with this PR, I might as well submit one more change:

I modified `MainActivity.kt` so that it parses all the NDEF records in all the messages present on an NFC tag, and search for text records containing a COVID certificate string, instead of forcing the tag to be formatted as a single message containing a single text record.

The idea, suggested by @craftbyte last month, is to allow an NFC tag to contain other information that may be used without the COVID verifier app. For example, a COVID certificate in the form of a smart poster containing human-readable information and images, as well as - somewhere in it - the `HC1:` string readable directly by the verifier app.

For instance, the following 2 test NDEFs may be read successfully with a bare-bone Android cellphone (as a sort of fallback of the verifier app isn't installed) as well as the verifier app:

[smart_poster-certificate_containing_only_text.ndef.zip](https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/files/7950876/smart_poster-certificate_containing_only_text.ndef.zip)
[smart_poster-certificate_containing_png_image.ndef.zip](https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/files/7950877/smart_poster-certificate_containing_png_image.ndef.zip)

2022-02-02 12:11 UTC, merged